name: CI

on:
  push:
    branches:
      - main  # You can change this to your project's main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14  # Specify the Node.js version you need

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test